modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="latticium"
version="${modVersion}"
displayName="Latticium"
logoFile="assets/latticium/icon.png"
description="Client construction engine"

[[mixins]]
config="latticium.mixins.json"
